/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:/tmp/gltfjsx-work/table.glb --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['table(Clone)']: THREE.Mesh
  }
  materials: {
    wood: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/table.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['table(Clone)'].geometry} material={materials.wood} />
    </group>
  )
}

useGLTF.preload('/table.glb')
